services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  web:
    build:
      context: ./frontend/web
    networks:
      - app-network
    depends_on:
      - backend

  mobile:
    build:
      context: ./frontend/mobile
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
