services:
  backend:
    container_name: tsukuruka-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "8080:8080"
  web:
    container_name: tsukuruka-frontend
    build:
      context: ./frontend/web
      target: dev
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mobile:
    build:
      context: ./frontend/mobile
      target: dev
    volumes:
      - ./frontend/mobile/src:/app/src
    env_file:
      - ./frontend/mobile/.env.dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
