services:
  backend:
    build:
      target: prod
    ports:
      - "8080:8080"
    environment:
      GO_ENV: prod

  web:
    build:
      target: prod
    ports:
      - "3000:3000"

  mobile:
    build:
      target: prod
    # 通常 mobile は本番では起動しない
    deploy:
      replicas: 0
volumes:
  postgres_data:
